[entrypoint]
url = "ws://127.0.0.1:8080/entrypoint"
key = "entrypoint_example_key"

[[nodes]]
hosts = [ "example.com", "www.example.com" ]
real_host = "127.0.0.1"
real_port = 8000
secure = false
allow_ws = false
